"""Chat interaction, code execution, and visualization specification models."""

from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


ChartType = Literal["bar", "line", "area", "pie", "scatter"]


class ChartSeries(BaseModel):
    """Specification of an individual data series/metric rendered on a chart."""

    key: str = Field(..., description="Key in the data object representing this series")
    name: str = Field(..., description="Human-readable label for legend and tooltips")
    color: Optional[str] = Field(default=None, description="Optional hex or css color code")


class ChartSpec(BaseModel):
    """Client-side Recharts chart configuration generated by the analysis code."""

    chart_type: ChartType = Field(..., description="Chart type: bar, line, area, pie, or scatter")
    title: str = Field(..., description="Chart title")
    x_key: str = Field(..., description="Key representing the X-axis or categorical dimension")
    series: List[ChartSeries] = Field(default_factory=list, description="List of data series to plot")
    data: List[Dict[str, Any]] = Field(default_factory=list, description="Data points for the chart")
    description: Optional[str] = Field(default=None, description="Short caption explaining the visual takeaway")


class TableData(BaseModel):
    """Tabular data representation for inline display, pagination, and CSV export."""

    columns: List[str] = Field(default_factory=list, description="Column names in display order")
    rows: List[Dict[str, Any]] = Field(default_factory=list, description="Row objects (column_name: cell_value)")
    total_rows: int = Field(default=0, description="Total number of rows in the complete result")


class ExecutionResult(BaseModel):
    """Output generated from running data analysis code against the session DataFrame."""

    success: bool = Field(..., description="True if code executed without errors")
    plan: str = Field(default="", description="Plain-English preliminary plan of steps")
    explanation: str = Field(default="", description="Plain-English explanation of calculations and findings")
    code: str = Field(default="", description="Python code that was executed")
    stdout: str = Field(default="", description="Standard output captured during execution")
    chart: Optional[ChartSpec] = Field(default=None, description="Optional interactive chart specification")
    table: Optional[TableData] = Field(default=None, description="Optional tabular output")
    error_traceback: Optional[str] = Field(default=None, description="Error traceback if execution failed")
    execution_time_ms: float = Field(default=0.0, description="Execution duration in milliseconds")
    retries_attempted: int = Field(default=0, description="Count of retry attempts required to succeed")


class ChatMessage(BaseModel):
    """An individual message in a session's conversation history."""

    id: str = Field(..., description="Unique message ID")
    role: Literal["user", "assistant", "system"] = Field(..., description="Sender role")
    content: str = Field(..., description="Main text content / plain-English answer")
    plan: Optional[str] = Field(default=None, description="Preliminary plan if assistant response")
    execution_result: Optional[ExecutionResult] = Field(default=None, description="Execution metadata and visuals")
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 timestamp"
    )
