#!/usr/bin/env python3
"""Generate and preflight Synopsys Design Compiler scripts for sample RTL.

This does not require a Design Compiler binary or license unless --run is used.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from run_synthesis import REPO_ROOT, TARGETS, _materialize_liberty, _target_liberty_files, build_project

CONFIG = REPO_ROOT / "config" / "dc_config.json"
DC_BUILD_DIR = REPO_ROOT / "build" / "dc"
RESULTS_DIR = REPO_ROOT / "results" / "dc"


def load_config(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as f:
        config = json.load(f)
    required = ["dc_shell_bin", "design", "compile", "targets"]
    missing = [key for key in required if key not in config]
    if missing:
        raise ValueError(f"Missing required config key(s): {', '.join(missing)}")
    return config


def _quote_tcl(value: Path | str) -> str:
    text = str(value)
    return "{" + text.replace("}", "\\}") + "}"


def _as_repo_path(path: str) -> Path:
    p = Path(path)
    return p if p.is_absolute() else REPO_ROOT / p


def _enabled_targets(config: dict[str, Any], requested: str) -> list[str]:
    configured = config.get("targets", {})
    if requested == "all":
        return [target for target in TARGETS if configured.get(target, {}).get("enabled", False)]
    if requested not in TARGETS:
        raise ValueError(f"Unsupported target '{requested}'. Choose one of: all, {', '.join(TARGETS)}")
    if not configured.get(requested, {}).get("enabled", False):
        raise ValueError(f"Target '{requested}' is disabled in {CONFIG}")
    return [requested]


def _resolve_liberty(config: dict[str, Any], target: str, workdir: Path) -> list[Path]:
    target_cfg = config["targets"][target]
    overrides = target_cfg.get("target_library_override", [])
    if overrides:
        return [_materialize_liberty(_as_repo_path(path), workdir) for path in overrides]

    project = build_project(target, config["design"].get("clock_period_ns", 10.0), jobname=f"dc_{target}")
    corner = target_cfg.get("liberty_corner")
    return [_materialize_liberty(path, workdir) for path in _target_liberty_files(project, corner)]


def _write_dc_tcl(config: dict[str, Any], target: str, liberty_files: list[Path], workdir: Path) -> Path:
    design = config["design"]
    compile_cfg = config["compile"]
    target_cfg = config["targets"][target]

    reports = workdir / "reports"
    outputs = workdir / "outputs"
    scripts = workdir / "scripts"
    for folder in (reports, outputs, scripts):
        folder.mkdir(parents=True, exist_ok=True)

    rtl_files = [_as_repo_path(path) for path in design.get("rtl", [])]
    search_dirs = sorted({str(path.parent) for path in rtl_files} | {str(path.parent) for path in liberty_files})
    link_libs = ["*"] + [str(path) for path in liberty_files] + [str(_as_repo_path(path)) for path in target_cfg.get("link_library_extra", [])]

    compile_command = compile_cfg.get("command", "compile_ultra")
    compile_args = []
    if compile_command == "compile_ultra" and not compile_cfg.get("ungroup", False):
        compile_args.append("-no_autoungroup")
    if compile_cfg.get("incremental", False):
        compile_args.append("-incremental")

    lines = [
        "# Auto-generated by scripts/setup_dc.py. Edit config/dc_config.json, not this file.",
        f"set DESIGN_NAME {_quote_tcl(design['name'])}",
        f"set TOP_MODULE {_quote_tcl(design['top'])}",
        f"set TARGET_NAME {_quote_tcl(target)}",
        f"set REPORT_DIR {_quote_tcl(reports)}",
        f"set OUTPUT_DIR {_quote_tcl(outputs)}",
        "file mkdir $REPORT_DIR",
        "file mkdir $OUTPUT_DIR",
        "",
        "set_app_var search_path [concat $search_path [list \\",
        *[f"    {_quote_tcl(path)} \\" for path in search_dirs],
        "] ]",
        f"set_app_var target_library [list {' '.join(_quote_tcl(path) for path in liberty_files)}]",
        f"set_app_var link_library [list {' '.join(_quote_tcl(path) for path in link_libs)}]",
        "",
    ]
    lines.extend(target_cfg.get("dc_setup_extra_tcl", []))
    lines.extend([
        "",
        f"analyze -format verilog [list {' '.join(_quote_tcl(path) for path in rtl_files)}]",
        "elaborate $TOP_MODULE",
        "current_design $TOP_MODULE",
        "link",
        "uniquify",
        f"create_clock -name {_quote_tcl(design.get('clock_name', 'clk'))} -period {float(design.get('clock_period_ns', 10.0))} [get_ports {_quote_tcl(design.get('clock_name', 'clk'))}]",
        f"set_dont_touch_network [get_ports {_quote_tcl(design.get('reset_name', 'rst_n'))}]",
        "check_design > $REPORT_DIR/check_design.rpt",
        f"{compile_command} {' '.join(compile_args)}".rstrip(),
        "report_qor > $REPORT_DIR/qor.rpt",
        "report_area -hierarchy > $REPORT_DIR/area.rpt",
        "report_timing -max_paths 20 > $REPORT_DIR/timing.rpt",
        "report_power > $REPORT_DIR/power.rpt",
        "write -format verilog -hierarchy -output $OUTPUT_DIR/${DESIGN_NAME}_${TARGET_NAME}.vg",
        "write -format ddc -hierarchy -output $OUTPUT_DIR/${DESIGN_NAME}_${TARGET_NAME}.ddc",
        "write_sdc $OUTPUT_DIR/${DESIGN_NAME}_${TARGET_NAME}.sdc",
        "exit",
        "",
    ])

    out = scripts / "dc_synth.tcl"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def preflight_target(config: dict[str, Any], target: str) -> dict[str, Any]:
    workdir = DC_BUILD_DIR / target
    workdir.mkdir(parents=True, exist_ok=True)
    liberty_files = _resolve_liberty(config, target, workdir)
    tcl = _write_dc_tcl(config, target, liberty_files, workdir)

    rtl_files = [_as_repo_path(path) for path in config["design"].get("rtl", [])]
    dc_shell_bin = config.get("dc_shell_bin", "dc_shell")
    dc_shell_path = shutil.which(dc_shell_bin) if dc_shell_bin else None
    license_env = config.get("license_env", {})
    license_status = {
        key: bool(value or os.environ.get(key))
        for key, value in license_env.items()
    }
    checks = {
        "rtl_files_exist": all(path.exists() for path in rtl_files),
        "liberty_files_exist": all(path.exists() for path in liberty_files),
        "dc_shell_found": bool(dc_shell_path),
        "license_env_present": any(license_status.values()) if license_status else False,
        "tcl_generated": tcl.exists(),
    }
    runnable = checks["rtl_files_exist"] and checks["liberty_files_exist"] and checks["dc_shell_found"] and checks["license_env_present"]
    result = {
        "design": config["design"]["name"],
        "topmodule": config["design"]["top"],
        "target": target,
        "status": "ready_to_run" if runnable else "preflight_only",
        "checks": checks,
        "dc_shell_bin": dc_shell_bin,
        "dc_shell_path": dc_shell_path,
        "license_env": license_status,
        "rtl": [str(path) for path in rtl_files],
        "liberty": [str(path) for path in liberty_files],
        "artifacts": {
            "workdir": str(workdir),
            "dc_tcl": str(tcl),
            "reports_dir": str(workdir / "reports"),
            "outputs_dir": str(workdir / "outputs"),
        },
    }
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    (RESULTS_DIR / f"{target}.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return result


def run_dc(config: dict[str, Any], target_result: dict[str, Any]) -> None:
    if target_result["status"] != "ready_to_run":
        raise RuntimeError(f"DC is not ready for {target_result['target']}; inspect preflight checks first")
    env = os.environ.copy()
    for key, value in config.get("license_env", {}).items():
        if value:
            env[key] = value
    log_path = Path(target_result["artifacts"]["workdir"]) / "dc_shell.log"
    with log_path.open("w", encoding="utf-8") as log:
        subprocess.run(
            [target_result["dc_shell_path"], "-f", target_result["artifacts"]["dc_tcl"]],
            cwd=target_result["artifacts"]["workdir"],
            env=env,
            stdout=log,
            stderr=subprocess.STDOUT,
            check=True,
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=CONFIG, help="Path to DC JSON config.")
    parser.add_argument("--target", choices=["all", *sorted(TARGETS)], default="all")
    parser.add_argument("--run", action="store_true", help="Invoke dc_shell after preflight passes.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    config = load_config(args.config)
    results = []
    for target in _enabled_targets(config, args.target):
        result = preflight_target(config, target)
        if args.run:
            run_dc(config, result)
        results.append(result)
        print(f"{target}: {result['status']} -> {result['artifacts']['dc_tcl']}")
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    (RESULTS_DIR / "summary.json").write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
